#!/bin/sh

set -E

echo "Detecting changed files.."
STAGED_FILES=$(git diff --cached --diff-filter=d --name-only)
[ -z "$STAGED_FILES" ] && exit 0

echo "Running Prettier..."
echo "$STAGED_FILES" | xargs npx prettier --ignore-unknown --write

echo "Staging changes..."
echo "$STAGED_FILES" | xargs git add
